#!/bin/bash -xe

exec 2>&1

echo "Seeding Mongo Collection"

source {{pkg.svc_config_path}}/mongoimport-opts.conf

$(hab pkg path core/mongo-tools)/bin/mongoimport --drop -d demo -c nationalparks --type json --jsonArray --file {{pkg.path}}/national-parks.json --host=$host --port=$port

echo "Starting Apache Tomcat"

export JAVA_HOME=$(hab pkg path core/jdk8)
export TOMCAT_HOME="$(hab pkg path core/tomcat8)/tc"

source {{pkg.svc_config_path}}/catalina-opts.conf

exec ${TOMCAT_HOME}/bin/catalina.sh run
